### PR TITLE
Initial russian translation

### PR DESCRIPTION
**Pull request by occune**
Sorry for opening another PR

### CODE REVIEW

**Comment by KaidemonLP** [comment]
Nothing to worry about. Everything seems fine this time.

**Comment by occune** [comment]
Is there any strings that i didn`t translate?

**Comment by KaidemonLP** [comment]
The china lake is missing a translation

**Comment by KaidemonLP** [comment]
Everything seems fine now. Thank you for your contribution!

**Comment by KaidemonLP** [comment]
One last question, under what name do you want to be credited?

**Comment by occune** [comment]
name that i use now on github and discord

**Pull request merged**
